version: '3.8'
services:
  nest-app:
    container_name: nest-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3050"
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: sso-db

  postgres:
    container_name: postgres-sso
    image: postgres:12.3
    environment:
      POSTGRES_PASSWORD: test123
    ports:
      - "5432:5432"